version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - './app:/app'
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'myapp'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
