version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    container_name: 'dbApp'
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      
  adminer:
    container_name: 'adminer'
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my-db:
